#!/bin/bash
fd -t f Makefile ./lab$1 -x sh -c 'cd "$(dirname "{}")" && make clean'

filename=ZurawelMarcin-cw0$1.tar.gz
tar cvzf compressed/$filename lab$1/*

if [[ $2 = "--wsl" ]]; then
    echo "Copying to Downloads..."
    cp compressed/$filename /mnt/c/Users/marci/Downloads/$filename 
fi
